import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from 'components/header/header'
import { ThemeProvider, createTheme } from '@mui/material/styles';
import Title from "@/components/title/title";
import Main from "@/components/main/main";
import Footer from "@/components/footer/footer";
import Content from "@/components/footer/content";

const inter = Inter({ subsets: ['latin'] })
const darkTheme = createTheme({
    palette: {
        mode: 'dark',
    },
});

export default function News() {
    return (
        <ThemeProvider theme={darkTheme}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Header/>
                <Title/>

                <Content/>
                <Footer/>
            </main>
        </ThemeProvider>
    )
}
