import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from 'components/header/header'
import { ThemeProvider, createTheme } from '@mui/material/styles';
import Title from "@/components/title/title";
import Footer from "@/components/footer/footer";
import Content from "@/components/footer/content";
import PhotoBlock from "@/components/main/photoBlock";
import React from "react";
import usePhotos from "@/lib/talons/usePhotos";

const inter = Inter({ subsets: ['latin'] })
const darkTheme = createTheme({
    palette: {
        mode: 'dark',
    },
});

export default function Price( props: any ) {

    const { sketchesList } = usePhotos()

    return (
        <ThemeProvider theme={darkTheme}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Header/>
                <Title/>
                    <article className="article">
                        <div className={'photoList'} >
                            {sketchesList.map((item, index) => (
                                <PhotoBlock key={index} data={sketchesList} src={item.src}/>
                            ))}
                        </div>
                    </article>
                <Content/>
                <Footer/>
            </main>
        </ThemeProvider>
    )
}
